#!/usr/bin/perl -w

use Dashboard;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "Dashboard",
   ReceiveHandler => \&Receive);
$UNIVERSAL::dashboard = Dashboard->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::dashboard->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::dashboard->Execute();
